# -*- coding: utf-8 -*-
"""GUI code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19abV1tjDDPqAQacXU9lVODJbTLgohKft
"""

!pip install gradio pandas matplotlib

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import os

# ---------------- DATA STORAGE ---------------- #
FILE = "expenses.csv"

if os.path.exists(FILE):
    expenses = pd.read_csv(FILE)
else:
    expenses = pd.DataFrame(columns=["Date","Category","Description","Amount"])

categories = ["Food","Transport","Books","Entertainment","Other"]
BUDGET_LIMIT = 200
WARNING_THRESHOLD = 0.8


# ---------------- FUNCTIONS ---------------- #

def add_expense(date, cat, desc, amt):
    global expenses

    if not date or not desc:
        return "❌ Please fill all fields", expenses

    try:
        amt = float(amt)
    except:
        return "❌ Invalid amount", expenses

    total_now = expenses["Amount"].sum() + amt

    if total_now > BUDGET_LIMIT:
        return "❌ Budget exceeded!", expenses

    new_row = pd.DataFrame([{
        "Date": str(date),
        "Category": cat,
        "Description": desc,
        "Amount": amt
    }])

    expenses = pd.concat([expenses, new_row], ignore_index=True)

    # SAVE TO CSV
    expenses.to_csv(FILE, index=False)

    msg = "✅ Expense added!"

    if expenses["Amount"].sum() >= BUDGET_LIMIT * WARNING_THRESHOLD:
        msg += "\n⚠️ Warning: Budget almost reached!"

    return msg, expenses


def show_total():
    total = expenses["Amount"].sum()
    return f"💰 Total spent: ${total:.2f} / {BUDGET_LIMIT}"


def show_category():
    if expenses.empty:
        return "No data"

    summary = expenses.groupby("Category")["Amount"].sum()
    return "\n".join([f"{c}: ${a:.2f}" for c,a in summary.items()])


def plot_chart():
    if expenses.empty:
        return None

    summary = expenses.groupby("Category")["Amount"].sum()

    fig, ax = plt.subplots()
    ax.pie(summary, labels=summary.index, autopct="%1.1f%%")
    ax.set_title("Spending Distribution")

    return fig


def suggestions():
    rem = BUDGET_LIMIT - expenses["Amount"].sum()
    per_cat = rem / len(categories) if len(categories) > 0 else 0

    text = f"Remaining: ${rem:.2f}\n\n"
    for c in categories:
        text += f"{c}: ~${per_cat:.2f}\n"

    return text


# ---------------- UI ---------------- #

with gr.Blocks() as app:

    gr.Markdown("## 💰 Smart Expense Tracker")
    gr.Markdown("Track your spending easily & stay within budget 📊")

    # -------- INPUT SECTION -------- #
    with gr.Group():
        gr.Markdown("### ➕ Add Expense")

        with gr.Row():
            date = gr.Textbox(
                label="📅 Date (YYYY-MM-DD)",
                placeholder="2026-03-22",
                lines=2
            )
            cat = gr.Dropdown(categories, label="📂 Category")

        desc = gr.Textbox(label="📝 Description", lines=3)
        amt = gr.Number(label="💵 Amount", precision=2)

        add_btn = gr.Button("➕ Add Expense")

        output_msg = gr.Textbox(label="Status", lines=3)

    # -------- TABLE -------- #
    with gr.Group():
        gr.Markdown("### 📋 Expense History")
        table = gr.Dataframe(value=expenses)

    # -------- ANALYTICS -------- #
    with gr.Group():
        gr.Markdown("### 📊 Insights")

        with gr.Row():
            total_btn = gr.Button("💰 Total")
            cat_btn = gr.Button("📊 Category View")

        total_out = gr.Textbox(lines=2)
        cat_out = gr.Textbox(lines=4)

    # -------- CHART & SUGGESTIONS -------- #
    with gr.Group():
        gr.Markdown("### 📈 Visuals & Tips")

        with gr.Row():
            plot_btn = gr.Button("📈 Show Chart")
            suggest_btn = gr.Button("💡 Suggestions")

        plot_out = gr.Plot()
        suggest_out = gr.Textbox(lines=5)

    # -------- ACTIONS -------- #
    add_btn.click(add_expense, [date, cat, desc, amt], [output_msg, table])
    total_btn.click(show_total, None, total_out)
    cat_btn.click(show_category, None, cat_out)
    plot_btn.click(plot_chart, None, plot_out)
    suggest_btn.click(suggestions, None, suggest_out)


app.launch()